In [37]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.model_selection import cross_val_score
import time 

In [15]:
X_train = pd.read_csv('./data/x_train.csv',header = 0)
y_train = pd.read_csv('./data/y_train.csv',header = 0)['0']
X_test = pd.read_csv('./data/x_test.csv',header = 0)
y_test = pd.read_csv('./data/y_test.csv',header = 0)['0']

In [16]:
train_weight = []
for i in range(10):
    train_weight.append(sum(y_train==i)/len(y_train))
class_weight = dict(zip(list(range(10)), train_weight))
C_range = [0.01,0.1,0.5,1,5]
solver_range=['newton-cg', 'sag', 'lbfgs']


In [170]:

accuracy_mat = np.empty(shape = (len(C_param_range),len(solver)))
for i in range(len(C_range)):
    for j in range(len(solver_range)):
        logreg = LogisticRegression(C=C_range[i],multi_class='multinomial',
                                    solver=solver_range[j],max_iter=4000,class_weight=class_weight)
        #logreg.fit(X_train, y_train)
        accuracy_mat[i,j] = np.mean(cross_val_score(logreg, X_train, y_train, cv=8,scoring = 'accuracy'))


/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was

/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/linear_model/sag.py:286: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [171]:
accuracy_mat

array([[  5.11734819e-001,   4.59701530e-001,   5.14356141e-001,
          7.26276499e-322],
       [  5.62343841e-001,   4.63544695e-001,   5.62439653e-001,
          7.46039125e-322],
       [  5.55745377e-001,   4.63544695e-001,   5.46622079e-001,
          7.65801751e-322],
       [  5.42726615e-001,   4.63544695e-001,   5.27163419e-001,
          7.85564377e-322],
       [  5.33833506e-001,   4.63544695e-001,   5.12244474e-001,
          8.05327003e-322],
       [  8.10267659e-322,   8.15208316e-322,   8.20148972e-322,
          8.25089629e-322]])

In [172]:
accuracy_mat = pd.DataFrame(accuracy_mat)

In [173]:
accuracy_mat

0              1              2              3
0   5.117348e-01   4.597015e-01   5.143561e-01  7.262765e-322
1   5.623438e-01   4.635447e-01   5.624397e-01  7.460391e-322
2   5.557454e-01   4.635447e-01   5.466221e-01  7.658018e-322
3   5.427266e-01   4.635447e-01   5.271634e-01  7.855644e-322
4   5.338335e-01   4.635447e-01   5.122445e-01  8.053270e-322
5  8.102677e-322  8.152083e-322  8.201490e-322  8.250896e-322

In [174]:
accuracy_mat.to_csv('accuracy_mat')

In [165]:
accuracy_mat = np.empty(shape = (len(C_range),len(solver_range)))
for i in range(len(C_range)):
    for j in range(len(solver_range)):
        accuracy_mat[i,j] = i*j+1

In [166]:
accuracy_mat

array([[  1.,   1.,   1.,   1.],
       [  1.,   2.,   3.,   4.],
       [  1.,   3.,   5.,   7.],
       [  1.,   4.,   7.,  10.],
       [  1.,   5.,   9.,  13.]])

In [192]:
X_train.head()

0           1          2          3          4          5  \
0 -202.558343  154.413094   6.078960  18.352162  16.465381  30.480092   
1 -213.265368    1.988407 -48.650124  23.510965  -7.462684  -3.799209   
2 -380.329943   73.198542 -39.966194 -20.987511  -4.460595  16.925125   
3 -138.287496   79.448712  20.735648  13.603314   7.975345   9.764178   
4 -413.884289  141.360328  18.207610  31.227967  27.038679  19.737574   

           6          7          8          9    ...           183        184  \
0  14.401530  20.897098  18.563433  14.471047    ...     14.456826  17.973174   
1   5.567173  12.748297 -14.672990   7.856349    ...     17.171133  15.628158   
2  22.688621  18.093317  -1.461838   6.899186    ...     17.288543  20.172915   
3  -5.277956   7.208292 -11.137283   9.889120    ...     19.416349  22.324888   
4  12.306729   9.493894   5.746234  11.782468    ...     16.754089  17.168880   

         185        186       187       188       189       190       191  \
0  16.108079  31.297310 -0.002555  0.028054 -0.027136 -0.030276  0.006397   
1  17.827012  34.033792  0.001401 -0.017233  0.056397 -0.035151 -0.011821   
2  20.075283  31.486941 -0.002645  0.003398  0.005168 -0.005238 -0.004769   
3  21.533164  34.027067  0.009196 -0.001665 -0.003320 -0.025083  0.008222   
4  16.950162  33.342208 -0.018952 -0.011458 -0.070440  0.048528 -0.018580   

        192  
0 -0.004940  
1 -0.013359  
2 -0.002136  
3 -0.004684  
4  0.007561  

[5 rows x 193 columns]

In [17]:
logreg = LogisticRegression(C=0.1,multi_class='multinomial',solver='lbfgs',max_iter=4000,class_weight=class_weight)

In [11]:
logreg = LogisticRegression(C=0.1,multi_class='multinomial',solver='lbfgs',max_iter=4000)

In [38]:
start = time.time()
logreg.fit(X_train, y_train)
end = time.time()
end - start

3.9631829261779785

In [19]:
y_pred = logreg.predict(X_test)

In [20]:
np.mean(y_pred==y_test)

0.60422960725075525

In [39]:
y_pred

array([5, 1, 3, 3, 6, 2, 9, 3, 9, 3, 4, 2, 0, 2, 9, 1, 9, 9, 3, 1, 3, 0, 1,
       3, 3, 9, 1, 1, 9, 3, 4, 9, 2, 2, 2, 3, 9, 9, 2, 3, 3, 2, 9, 9, 3, 5,
       3, 3, 3, 9, 5, 3, 8, 2, 3, 2, 5, 9, 3, 3, 3, 9, 4, 6, 3, 9, 3, 9, 9,
       2, 9, 6, 3, 8, 3, 3, 1, 9, 8, 3, 3, 9, 2, 3, 3, 3, 3, 5, 3, 1, 9, 3,
       3, 3, 8, 3, 3, 3, 3, 3, 6, 9, 9, 3, 1, 2, 3, 3, 9, 1, 4, 8, 3, 6, 3,
       3, 5, 3, 9, 3, 6, 2, 9, 3, 2, 9, 3, 3, 2, 3, 2, 3, 3, 2, 3, 9, 9, 2,
       5, 6, 2, 2, 2, 3, 3, 4, 2, 4, 9, 6, 4, 4, 1, 9, 6, 5, 3, 3, 3, 3, 3,
       4, 8, 3, 5, 1, 6, 9, 3, 2, 3, 6, 3, 8, 9, 1, 2, 2, 3, 9, 6, 3, 3, 3,
       3, 1, 3, 3, 3, 4, 6, 3, 3, 3, 3, 3, 3, 0, 2, 9, 3, 9, 3, 3, 4, 9, 3,
       3, 3, 8, 5, 9, 3, 2, 4, 5, 4, 4, 5, 3, 3, 9, 4, 3, 3, 8, 1, 3, 2, 4,
       3, 1, 3, 6, 2, 4, 9, 9, 3, 3, 2, 4, 6, 9, 6, 4, 3, 8, 3, 7, 3, 9, 3,
       4, 3, 9, 3, 2, 3, 9, 9, 3, 3, 9, 3, 1, 6, 8, 9, 4, 6, 2, 2, 1, 3, 1,
       3, 3, 3, 8, 5, 6, 0, 2, 9, 2, 3, 2, 4, 2, 9, 2, 9, 3, 3, 8, 1, 3, 3,
       1, 1,

In [43]:
each_accuracy = []
for i in range(10):
    acc = sum(y_pred[y_test == i] == y_test[y_test==i])/sum(y_test==i)
    acc = float(str(round(acc,2)))
    each_accuracy.append(acc)
    
each_accuracy

[0.18, 0.51, 0.56, 0.82, 0.5, 0.48, 0.66, 0.17, 0.53, 0.64]

In [191]:
y_pred_train = logreg.predict(X_train)
np.mean(y_pred_train==y_train)

0.75616083009079116

In [229]:
list(range(6,11))

[6, 7, 8, 9, 10]

In [242]:
index_train = [y in range(5,10) for y in y_train]
index_test = [y in range(5,10) for y in y_test]

In [234]:
len(y_train)

771

In [240]:
sum(index_train)

560

In [243]:
logreg = LogisticRegression(C=0.1,multi_class='multinomial',solver='lbfgs',max_iter=4000)
logreg.fit(X_train[index_train], y_train[index_train])
y_pred = logreg.predict(X_test[index_test])
np.mean(y_pred==y_test[index_test])

0.69230769230769229

In [38]:
str(list(range(10)))

'[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]'

In [42]:
class_weight = dict(zip(list(range(10)), train_weight))

In [43]:
class_weight

{0: 0.033232628398791542,
 1: 0.10574018126888217,
 2: 0.12386706948640483,
 3: 0.25377643504531722,
 4: 0.090634441087613288,
 5: 0.069486404833836862,
 6: 0.10574018126888217,
 7: 0.036253776435045321,
 8: 0.045317220543806644,
 9: 0.13595166163141995}

In [31]:
test_weight = []
for i in range(10):
    test_weight.append(sum(y_test==i)/len(y_test))

In [34]:
test_weight

[0.033232628398791542,
 0.10574018126888217,
 0.12386706948640483,
 0.25377643504531722,
 0.090634441087613288,
 0.069486404833836862,
 0.10574018126888217,
 0.036253776435045321,
 0.045317220543806644,
 0.13595166163141995]

In [35]:
train_weight = []
for i in range(10):
    train_weight.append(sum(y_train==i)/len(y_train))

In [36]:
train_weight

[0.045395590142671853,
 0.10376134889753567,
 0.1245136186770428,
 0.24773022049286642,
 0.089494163424124515,
 0.068741893644617386,
 0.098573281452658881,
 0.027237354085603113,
 0.064850843060959798,
 0.1297016861219196]

In [64]:

cross_val_score(logreg, X_train, y_train, cv=10,scoring = 'accuracy')

/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the number of iterations.
  "number of iterations.", ConvergenceWarning)
/Users/linhan/anaconda/lib/python3.6/site-packages/sklearn/utils/optimize.py:203: ConvergenceWarning: newton-cg failed to converge. Increase the

KeyboardInterrupt: 

In [63]:
?cross_val_score